fix(package): bump elastic-apm to version 4.5.0
elastic/opbeans-ruby pull request #122
Opened 2022-04-27 10:26 UTC by v1v

Update lock and docker metadata.

Then I'll create the tag release

Dependabot has been bumping the versions but missed to update the Gemfile.lock and docker images as per described in https://github.com/elastic/opbeans-ruby/blob/main/.ci/bump-version.sh

The automation relies on the git tags for the apm-agent-ruby, which were disabled for a period of time, but dependabot seems to be doing its job

2022-04-27 10:36 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fopbeans-ruby-mbp%2FPR-122/detail/PR-122/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fopbeans-ruby-mbp%2FPR-122/detail/PR-122/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fopbeans-ruby-mbp%2FPR-122/detail/PR-122/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fopbeans-ruby-mbp%2FPR-122/detail/PR-122/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://opbeans-ruby_122.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-04-27T10:17:00.345Z&rangeTo=2022-04-27T10:37:00.345Z&transactionName=apm-agent-ruby/opbeans-ruby-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=d49b1a87d167eca18dff17196a665ac7&transactionId=1af9699eee5ea715)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-27T10:27:00.345+0000


* Duration: 10 min 31 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 6  |
| Skipped      | 0 |
| Total        | 6   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-27 14:21 UTC, amannocci requested changes
It seems that the bump-version.sh script don't set properly BUNDLE_VERSION env variable during bump step and as a result we can be in a situation where BUNDLER_VERSION is different from version in Gemfile.lock.
To avoid conflict, we should ensure that both versions match.

2022-04-28 11:39 UTC, v1v commented on Gemfile.lock
> +   2.3.12
```suggestion
   2.2.22
```

2022-04-28 11:43 UTC, amannocci approved these changes
LGTM

2022-04-28 12:03 UTC, merged